FROM debian:stable-slim

RUN apt update -y && apt upgrade -y
RUN apt install -y libssl3 libcurl4 libsqlite3-0 libmariadb3 gdb

WORKDIR /block

COPY block block
COPY block_d block_d
COPY libantibot.so libantibot.so
COPY storage.cfg .
COPY start.sh .

EXPOSE 8303/udp

RUN chmod +x ./start.sh

ENTRYPOINT [ "./start.sh" ]