#ifndef BLOCKWORLDS_COMMON_H
#define BLOCKWORLDS_COMMON_H

enum ExpCalculationMethod
{
	HIGHEST = 0,
	ADDITIVE,
	LOGARITHMIC,
	MULTIPLICATIVE,
	NUM_EXP_CALC_METHODS
};

#endif // BLOCKWORLDS_COMMON_H
