stages:
#  - Build buildtools image
  - Build DDNet Server
  - Build docker image and deploy

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  CCACHE_DIR: $CI_PROJECT_DIR/.ccache
  CARGO_INCREMENTAL: "true"

# TODO: make this work
# build_buildtools_image:
#   stage: Build buildtools image
#   image:
#     name: gcr.io/kaniko-project/executor:v1.23.2-debug
#     entrypoint: [""]
#   variables:
#     IMAGE_TAG: ${CI_REGISTRY_IMAGE}/buildtools:latest
#   script:
#     - mkdir -p /kaniko/.docker
#     - echo "{\"auths\":{\"registry.gitlab.com\":{\"auth\":\"$(printf "%s:%s" "${GL_DEPLOY_USER}" "${GL_DEPLOY_PASS}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
#     - /kaniko/executor
#       --snapshot-mode=redo
#       --compressed-caching=false
#       --context "${CI_PROJECT_DIR}"
#       --dockerfile "${CI_PROJECT_DIR}/Dockerfile.buildtools"
#       --destination "${IMAGE_TAG}"
#   rules:
#     - changes:
#         - Dockerfile.buildtools


.ddnet_build_base:
  stage: Build DDNet Server
  image: registry.gitlab.com/blockworlds1/blockworlds/buildtools:latest
  cache:
    key: "cache-$CI_COMMIT_REF_SLUG-$BUILD_TYPE"
    paths:
      - .cargo/
      - .ccache/
      - build/_deps/
  before_script:
    - export CCACHE_DIR=$CI_PROJECT_DIR/.ccache
    - export CARGO_HOME=$CI_PROJECT_DIR/.cargo
    - export CC=clang
    - export CXX=clang++
  only:
    - master
    - test

build_release:
  extends: .ddnet_build_base
  variables:
    BUILD_TYPE: "Release"
  script:
    - mkdir build && cd build
    - cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCLIENT=OFF -DTOOLS=OFF -DDEV=ON -DMYSQL=ON -DANTIBOT=ON -DUPNP=OFF -DWEBSOCKETS=OFF -DVULKAN=OFF -DGFX=OFF ..
    - ninja game-server
    - cp DDNet-Server ../blockworlds
    - cp libantibot.so ../libantibot.so
  artifacts:
    paths:
      - blockworlds
      - libantibot.so
    expire_in: 7 days

build_debug:
  extends: .ddnet_build_base
  variables:
    BUILD_TYPE: "Debug"
  script:
    - mkdir build && cd build
    - cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCLIENT=OFF -DTOOLS=OFF -DDEV=ON -DMYSQL=ON -DANTIBOT=ON -DUPNP=OFF -DWEBSOCKETS=OFF -DVULKAN=OFF -DGFX=OFF ..
    - ninja game-server
    - cp DDNet-Server ../blockworlds_d
  artifacts:
    paths:
      - blockworlds_d
    expire_in: 7 days

package_main:
  stage: Build docker image and deploy
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  variables:
    IMAGE_LATEST: ${CI_REGISTRY_IMAGE}:latest
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"registry.gitlab.com\":{\"auth\":\"$(printf "%s:%s" "${GL_DEPLOY_USER}" "${GL_DEPLOY_PASS}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile.blockworlds"
      --destination "${IMAGE_LATEST}"
  only:
    - master


package_test:
  stage: Build docker image and deploy
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  variables:
    IMAGE_LATEST: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"registry.gitlab.com\":{\"auth\":\"$(printf "%s:%s" "${GL_DEPLOY_USER}" "${GL_DEPLOY_PASS}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile.blockworlds"
      --destination "${IMAGE_LATEST}"
  only:
    - test
