image: ubuntu:22.04

stages:
  - Build DDNet Server
  - Build docker image and deploy

build_cmake_release:
  stage: Build DDNet Server
  before_script:
    - apt-get update -y
    - apt-get upgrade -y
    - apt-get install
      pkg-config
      clang rustc
      cargo cmake ninja-build
      libmariadb-dev
      libcurl4-openssl-dev
      libssl-dev
      zlib1g-dev
      libsqlite3-dev
      sqlite3
      libpng-dev
      valgrind -y
  script:
    # Build Release
    - mkdir build && cd build
    - export CC=clang
    - export CXX=clang++
    - cmake -GNinja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCLIENT=OFF -DTOOLS=OFF -DDEV=ON -DMYSQL=ON -DANTIBOT=ON -DUPNP=OFF -DWEBSOCKETS=OFF -DVULKAN=OFF -DGFX=OFF ..
    - ninja game-server
    - cp DDNet-Server ../blockworlds
    - cp libantibot.so ../libantibot.so
    # Build Debug
    - rm -rf *
    - export CC=clang
    - export CXX=clang++
    - cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCLIENT=OFF -DTOOLS=OFF -DDEV=ON -DMYSQL=ON -DANTIBOT=ON -DUPNP=OFF -DWEBSOCKETS=OFF -DVULKAN=OFF -DGFX=OFF ..
    - ninja game-server
    - cp DDNet-Server ../blockworlds_d
    

  artifacts:
    paths:
      - blockworlds
      - blockworlds_d
      - libantibot.so
    when: on_success
    expire_in: 7 days
  only:
    - master
    - test

package_main:
  stage: Build docker image and deploy
  image: docker:29.0.0-alpine3.22
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    IMAGE_LATEST: registry.gitlab.com/blockworlds1/blockworlds:latest
  script:
    - docker info
    - docker login registry.gitlab.com -u ${GL_DEPLOY_USER} -p ${GL_DEPLOY_PASS}
    - DOCKER_BUILDKIT=1 docker build -f Dockerfile.blockworlds -t $IMAGE_LATEST .
    - docker push $IMAGE_LATEST
  only:
    - master

package_test:
  stage: Build docker image and deploy
  image: docker:29.0.0-alpine3.22
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    IMAGE_LATEST: registry.gitlab.com/blockworlds1/blockworlds:${CI_COMMIT_BRANCH}
  script:
    - docker info
    - docker login registry.gitlab.com -u ${GL_DEPLOY_USER} -p ${GL_DEPLOY_PASS}
    - DOCKER_BUILDKIT=1 docker build -f Dockerfile.blockworlds -t $IMAGE_LATEST .
    - docker push $IMAGE_LATEST
  only:
    - test